app/views/login/forms.py
from flask.app import Flask
from flask_wtf import FlaskForm
from wtforms import StringField, PasswordField
from wtforms import SubmitField
from wtforms import EmailField
from wtforms import TelField
from wtforms import RadioField
from wtforms import TextAreaField
from wtforms.fields.simple import TextAreaField
from wtforms.validators import DataRequired
from wtforms.validators import Length
from wtforms.validators import EqualTo
from wtforms.validators import Email
from .validators import UniqueEmail


class LoginForm(FlaskForm):
    email_address = EmailField('E-mail',
        validators=[DataRequired(), Email()])
    password = PasswordField('Password', 
        validators=[DataRequired()])
    submit = SubmitField('Login')


class RegistrationForm(FlaskForm):
    first_name = StringField('First Name *',
        validators=[DataRequired(), Length(min=2, max=50)])
    middle_name = StringField('Middle Name',
        validators=[Length(min=0, max=50)])
    last_name = StringField('Last Name *',
        validators=[DataRequired(), Length(min=2, max=50)])
    phone_number = TelField('Phone Number *',
        validators=[DataRequired(), Length(min=11, max=11)])
    account_type = RadioField('Account Type',
        choices=[('indiv-donor', 'Individial Donor'), 
                 ('org-donor', 'Organization Donor'), 
                 ('collector', 'Collector')])
    street = StringField('Street *',
        validators=[DataRequired(), Length(min=5, max=50)])
    barangay = StringField('Barangay *',
        validators=[DataRequired(), Length(min=5, max=50)])
    city = StringField('City *',
        validators=[DataRequired(), Length(min=5, max=50)])
    org_name = StringField('Organization Name',
        validators=[Length(min=0, max=100)])
    about = TextAreaField('About',
        validators=[Length(min=0, max=250)])
    email_address = EmailField('E-mail *',
        validators=[DataRequired(), Email(), UniqueEmail()])
    password = PasswordField('Password *',
        validators=[DataRequired(), Length(min=8, max=50)])
    confirm_password = PasswordField('Confirm Password *',
        validators=[DataRequired(), EqualTo('password')])
    submit = SubmitField('Register')
            

class ResetPasswordForm(FlaskForm):
    email_address = EmailField('E-mail',
        validators=[DataRequired(), Email()])
    submit = SubmitField('Get Reset Code')


class VerifyCodeForm(FlaskForm):
    code = StringField('Reset Code',
        validators=[DataRequired()])
    submit = SubmitField('Submit')


class NewPasswordForm(FlaskForm):
    new_password = PasswordField('New Password',
        validators=[DataRequired()])
    confirm_password = PasswordField('Confirm Password',
        validators=[DataRequired(), EqualTo('new_password')])
    submit = SubmitField('Submit')


                                    

app/views/login/__init__.py
from flask import Blueprint

login_bp = Blueprint('login', __name__)

from . import routes

app/views/login/routes.py
from flask.helpers import url_for
from werkzeug.utils import redirect
from flask import flash
from flask import render_template
from flask import request
from flask import session
from ...models.user import User
from .forms import LoginForm
from .forms import RegistrationForm
from .forms import ResetPasswordForm
from .forms import VerifyCodeForm
from .forms import NewPasswordForm
from .utils import user_found
from .utils import hash_password
from .utils import get_role_id
from .utils import random_characters
from .utils import gmail_code
from .utils import check_email_registration
from .utils import save_new_password
from .utils import get_role
from . import login_bp


@login_bp.route("/login", methods=["GET", "POST"])
def login() -> str:
    form = LoginForm()
    reg_form = RegistrationForm()
    if request.method == "POST":
        email_address = request.form.get("email_address")
        password = request.form.get("password")
        if user_found(email_address, password):
            session["role"] = get_role(email_address)
            session["status"] = "logged-in"
            session["email_address"] = email_address
            if session["role"] == "collector":
                return redirect(url_for("collectors_view.collectors_view"))
            else:
                return redirect(url_for("donation_feed.posted_donations"))
        else:
            flash(f"User not found.", "error")
            return render_template("/login/base.html", form=form, reg_form=reg_form)
    elif "email_address" in session:
        if session["role"] == "collector":
            return redirect(url_for("collectors_view.collectors_view"))
        else:
            return redirect(url_for("donation_feed.posted_donations"))
    return render_template("/login/base.html", form=form, reg_form=reg_form)


@login_bp.route("/create account", methods=["GET", "POST"])
def register() -> str:
    form = RegistrationForm(request.form)
    if form.validate_on_submit():
        first_name = request.form.get("first_name")
        middle_name = request.form.get("middle_name")
        last_name = request.form.get("last_name")
        phone_number = request.form.get("phone_number")
        user_role = request.form.get("account_type")
        user_role = get_role_id(user_role)
        street = request.form.get("street")
        barangay = request.form.get("barangay")
        city = request.form.get("city")
        org_name = request.form.get("org_name")
        about = request.form.get("about")
        email_address = request.form.get("email_address")
        password = request.form.get("password")
        password = hash_password(password)
        User(
            first_name=first_name,
            middle_name=middle_name,
            last_name=last_name,
            email=email_address,
            password=password,
            phone_number=phone_number,
            street=street,
            barangay=barangay,
            city=city,
            org_name=org_name,
            about=about,
            user_role=user_role,
        ).add_new()
        session["email_address"] = email_address
        session["role"] = request.form.get("account_type")
    else:
        flash(
            "Registration failed. E-mail, Phone Number, and Organization Name must be unique.",
            "info",
        )
    return redirect(url_for("login.login"))


@login_bp.route("/reset password", methods=["GET", "POST"])
def reset_password() -> str:
    form = ResetPasswordForm()
    reg_form = RegistrationForm()
    if request.method == "POST":
        email = request.form.get("email_address")
        registered_email = check_email_registration(email)
        if registered_email:
            session["email"] = email
            reset_code = random_characters()
            session["reset_code"] = reset_code
            gmail_code(reset_code, email)
            code_form = VerifyCodeForm()
            return render_template(
                "/login/enter_code.html",
                email=session["email"],
                form=code_form,
                reg_form=reg_form,
            )
        else:
            flash(f"That email address is not registered.", "info")
            return render_template(
                "/login/get_email.html", form=form, reg_form=reg_form
            )
    return render_template("/login/get_email.html", form=form, reg_form=reg_form)


@login_bp.route("/verify code", methods=["POST"])
def verify_code():
    form = NewPasswordForm()
    reg_form = RegistrationForm()
    if request.method == "POST":
        user_input = request.form.get("code")
        if user_input == session["reset_code"]:
            return render_template(
                "/login/new_password.html", form=form, reg_form=reg_form
            )
        else:
            flash(f"Incorrect code.", "info")
            return render_template(
                "/login/enter_code.html",
                form=form,
                reg_form=reg_form,
                email=session["email"],
            )


@login_bp.route("/check new password", methods=["POST"])
def check_new_password():
    form = NewPasswordForm(request.form)
    if request.method == "POST" and form.validate_on_submit():
        new_password = request.form.get("new_password")
        save_new_password(session["email"], new_password)
        return redirect(url_for("login.login"))
    else:
        form = NewPasswordForm()
        flash(f"Password did not match. Try again", "info")
        return render_template("/login/new_password.html", form=form)


@login_bp.route("/logout")
def logout():
    session.clear()
    return redirect(url_for("login.login"))

app/templates/login/base.html
{% extends "master.html" %}
{% include "/includes/modals.html" %}

{% block title %}Food Donation - Login{% endblock %}
{% block style %}
    <link rel="stylesheet" type="text/css"
    href="{{url_for('static', filename='css/login/login.css')}}">
    <link rel="stylesheet" type="text/css"
    href="{{url_for('static', filename='css/login/utils.css')}}">
{% endblock %}
{% include "/layouts/master_layout.html" %}
{% block body %}
<div class="limiter">
  <div class="container-login100" style="background-image: url('https://res.cloudinary.com/deh9vgcga/image/upload/v1638613132/bg_jeqlma.jpg');">
    <div class="wrap-login100 p-t-190 p-b-30">
      {% block form %}
      <form class="login100-form validate-form" action="{{url_for('login.login')}}" method="post">
        {{ form.hidden_tag() }}
        {{ form.csrf_token() }}
        <span class="login100-form-title p-t-20 p-b-45">
          {% block header %}
          Welcome!
          {% endblock %}
        </span>

        <div class="wrap-input100 validate-input m-b-10">
          {{ form.email_address(class='input100', placeholder='Email Address')}}
          <span class="focus-input100"></span>
          <span class="symbol-input100">
            <i class="fa fa-envelope"></i>
          </span>
        </div>

        <div class="wrap-input100 validate-input m-b-5">
          {{ form.password(class='input100', placeholder='Password')}}
          <span class="focus-input100"></span>
          <span class="symbol-input100">
            <i class="fa fa-lock"></i>
          </span>
        </div>

        <div class="container-login100-form-btn p-t-0">
          {{ form.submit(class='login100-form-btn btn-success')}}
        </div>
        {% include "/includes/alert_message.html"%}
          <div class="links wrap-input100">
            {% block link %}
            <a href="" class="create-account-link txt1" data-bs-toggle="modal" data-bs-target="#choose-role">Don't have an account? Register here</a>
            <br>
            <a href="{{url_for('login.reset_password')}}" class="forgot-password-link txt1">Forgot password?</a>
            {% endblock %}
          </div>
      </form>
      {% endblock %}
    </div>
  </div>
</div>
{% endblock %}

app/templates/login/enter_code.html
{% extends "login/base.html" %}

{% block title %}Food Donation - Reset Password{% endblock %}
{% block header %}Forgot Password{% endblock %}
{% block form %}
<form class="login100-form validate-form" action="{{url_for('login.verify_code')}}" method="post">
  {{ form.hidden_tag() }}
  {{ form.csrf_token() }}
  <div class="wrap-input100 validate-input m-b-10">
    {{ form.code(class='input100', placeholder='Enter reset code')}}
    <span class="focus-input100"></span>
    <span class="symbol-input100">
      <i class="fa fa-envelope"></i>
    </span>
  </div>
  <p class="ec_message wrap-input100">Reset code is sent to {{email}}</p>
  {% include "/includes/alert_message.html"%}
  <div class="container-login100-form-btn p-t-10">
    {{ form.submit(class='login100-form-btn btn-success')}}
  </div>
  <div class="links wrap-input100">
    {% block link %}
    <a href="{{url_for('login.register')}}" class="create-account-link txt1">Don't have an account? Register here</a>
    {% endblock %}
  </div>
</form>
{% endblock %}

app/templates/login/get_email.html
{% extends "login/base.html" %}

{% block title %}Food Donation - Reset Password{% endblock %}
{% block header %}Forgot Password{% endblock %}
{% block form %}
<form class="login100-form validate-form" action="{{url_for('login.reset_password')}}" method="post">
  {{ form.hidden_tag() }}
  {{ form.csrf_token() }}

  <div class="wrap-input100 validate-input m-b-10">
    {{ form.email_address(class='input100', placeholder='Enter your registered E-mail Address')}}
    <span class="focus-input100"></span>
    <span class="symbol-input100">
      <i class="fa fa-envelope"></i>
    </span>
  </div>
  {% include "/includes/alert_message.html"%}
  <div class="container-login100-form-btn p-t-10">
    {{ form.submit(class='login100-form-btn btn-success')}}
  </div>

  <div class="links wrap-input100">
    {% block link %}
    <a href="" class="create-account-link txt1" data-bs-toggle="modal" data-bs-target="#choose-role">Don't have an account? Register here</a>
    {% endblock %}
  </div>
</form>
{% endblock %}

app/templates/login/new_password.html
{% extends "login/base.html" %}

{% block title %}Food Donation - Reset Password{% endblock %}
{% block header %}Forgot Password{% endblock %}
{% block form %}
<form class="login100-form validate-form" action="{{url_for('login.reset_password')}}" method="post">
  {{ form.hidden_tag() }}
  {{ form.csrf_token() }}

  <div class="wrap-input100 validate-input m-b-10">
    {{ form.email_address(class='input100', placeholder='Enter your registered E-mail Address')}}
    <span class="focus-input100"></span>
    <span class="symbol-input100">
      <i class="fa fa-envelope"></i>
    </span>
  </div>
  {% include "/includes/alert_message.html"%}
  <div class="container-login100-form-btn p-t-10">
    {{ form.submit(class='login100-form-btn btn-success')}}
  </div>

  <div class="links wrap-input100">
    {% block link %}
    <a href="" class="create-account-link txt1" data-bs-toggle="modal" data-bs-target="#choose-role">Don't have an account? Register here</a>
    {% endblock %}
  </div>
</form>
{% endblock %}

app/templates/login/register.html
{% extends "login/base.html" %}

{% block title %}Food Donation - Sign Up{% endblock %}
{% block header %}Create an account{% endblock %}
{% block form %}
<form action="{{url_for('login.register')}}" method="post">
    {{ form.hidden_tag() }}
    {{ form.csrf_token() }}
    <div class="form-group">
      {{ form.first_name.label }}
      {{ form.first_name(id='first_name', class='form-control', required=True) }}
    </div>
    <div class="form-group">
      {{ form.middle_name.label }}
      {{ form.middle_name(id='middle_name', class='form-control') }}
    </div>
    <div class="form-group">
      {{ form.last_name.label }}
      {{ form.last_name(id='last_name', class='form-control', required=True) }}
    </div>
    <div class="form-group">
      {{ form.email_address.label }}
      {{ form.email_address(id='email_address', class='form-control', required=True, placeholder="Use an active email") }}
    </div>
    <div class="form-group mb-4">
      {{ form.phone_number.label }}
      {{ form.phone_number(id='phone_number', class='form-control', required=True, pattern="^((\+63)|0)\d{10}$") }}
    </div>
    <br>
    <p>Please select your account type:</p>
    <div class="form-check">
      {{ form.account_type(id='account_type') }}
    </div>
    <br>
    <h5>Address</h5>
    <div class="form-group mb-4">
      {{ form.street.label }}
      {{ form.street(id='street', class='form-control', required=True) }}
    </div>
    <div class="form-group mb-4">
      {{ form.barangay.label }}
      {{ form.barangay(id='barangay', class='form-control', required=True) }}
    </div>
    <div class="form-group mb-4">
      {{ form.city.label }}
      {{ form.city(id='city', class='form-control', required=True) }}
    </div>
    <br>
    <h5>Login Credentials</h5>
    <div class="form-group">
      {{ form.username.label }}
      {{ form.username(id='username', class='form-control', required=True) }}
    </div>
    <div class="form-group mb-4">
      {{ form.password.label }}
      {{ form.password(id='password', class='form-control', required=True) }}
    </div>
    <div class="form-group mb-4">
      {{ form.confirm_password.label }}
      {{ form.confirm_password(id='confirm_password', class='form-control', required=True) }}
    </div>
    <div class="form-group mb-4">
      {{ form.submit(class='btn btn-block login-btn mb-4')}}
    </div>
 </form>
 {% endblock %}
{% block link %}
<!-- <a href="#!" class="forgot-password-link">Forgot password?</a> -->
<p class="login-card-footer-text">Already have an account? <a href="{{url_for('login.login')}}" class="text-reset">Login here</a></p>
{% endblock %}