app/views/dashboard/__init__.py
from flask import Blueprint

dashboard_bp = Blueprint('dashboard', __name__)

from . import routes

app/views/dashboard/routes.py
from werkzeug.exceptions import SecurityError
from werkzeug.utils import redirect
from . import dashboard_bp
from flask import render_template, session, url_for, request, flash
from . import utils

@dashboard_bp.route('/donor/dashboard')
def donor_dashboard() -> str:
    if 'email_address' in session:
        donor_details =  utils.show_donor_details(session["email_address"])
        donations_kls = utils.get_total_foods(session["email_address"])
        beverages_ltr = utils.get_total_beverages(session["email_address"])
        food_distributed = utils.get_total_food_distributed(session["email_address"])
        bev_distributed = utils.get_total_bev_distributed(session["email_address"])
        collectors = utils.get_collectors(session["email_address"])
       

        return render_template('dashboard/donor_dashboard.html', donor = donor_details, 
            donations_kls = donations_kls,  beverages_ltr = beverages_ltr,  bev_distributed = bev_distributed,
            food_distributed=food_distributed, collectors = collectors) 
    else:
        return render_template('login/base.html')

@dashboard_bp.route('/collector/dashboard')
def collector_dashboard():
    if 'email_address' in session:
        donor_details =  utils.show_donor_details(session["email_address"])
        food_distributed = utils.get_total_food_bev_distributed(session["email_address"])
        our_donors = utils.get_organization_donors(session["email_address"])
       
        return redirect(url_for('collectors_view.collectors_view'))
    else:
        return redirect(url_for('login.login'))


@dashboard_bp.route('/collector/dashboard/to distribute')
def to_distribute():
    if 'email_address' in session:
        donor_details =  utils.show_donor_details(session["email_address"])
        collections = utils.get_items_for_distribution(session["email_address"])
        collections.reverse()
        return render_template('dashboard/org_to_distribute.html', donor = donor_details, collections=collections)

@dashboard_bp.route('/collector/dashboard/distributed', methods=['POST'])
def distribute():
    if 'email_address' in session:
        image_link1 = request.files['image_file1']
        image_link2 = request.files['image_file2']
        image_link3 = request.files['image_file3']
        img_storage = [image_link1, image_link2, image_link3]
        images = []
        for image in img_storage:
            if image.filename:
                img_link = utils.get_image_url(image)
                images.append(img_link)
        donation_id = request.args.get('id')
        utils.set_distributed_to_true(donation_id)
        utils.save_distribution_images(donation_id, images)
        utils.record_distribution(donation_id)
        return redirect(url_for('dashboard.to_distribute'))


@dashboard_bp.route('/collector/dashboard/to recieve')
def to_recieve():
    if 'email_address' in session:
        donor_details =  utils.show_donor_details(session["email_address"])
        reserves = utils.get_items_to_collect(session["email_address"])
        reserves.reverse()
        return render_template('dashboard/org_to_collect.html', donor = donor_details, reserves=reserves)


@dashboard_bp.route('/collector/dashboard/recieved or collected')
def recieve_collect():
    if 'email_address' in session:
        donation_id = request.args.get('id')
        utils.set_collected_to_true(donation_id)
        return redirect(url_for('dashboard.to_recieve'))

@dashboard_bp.route('/collector/dashboard/completed collection')
def completed_collection():
    if 'email_address' in session:
        donor_details =  utils.show_donor_details(session["email_address"])
        completed = utils.get_completed_collections(session['email_address'])
        completed.reverse()
        return render_template('dashboard/org_completed.html', donor = donor_details, completed=completed)

        
@dashboard_bp.route('/collector/dashboard/cancel')
def collect_cancel():
    if 'email_address' in session:
        donation_id = request.args.get('id')
        utils.set_collected_to_false(donation_id)
        return redirect(url_for('dashboard.to_recieve'))

app/templates/dashboard/base.html
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="UTF-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <title>{% block title %} {% endblock %}</title>
        
        <!-- Bootstrap CSS -->
        <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
        <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.5.0/font/bootstrap-icons.css">
        <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.0.7/css/all.css">
        {% block css_link %} {% endblock %}
    </head>
    <header>
        {% block navbar %} {% endblock navbar %}
    </header>
<body>
    {% block main_content %}
        
    {% endblock main_content %}


        <!-- JavaScript Bundle with Popper -->
        <!-- JavaScript Bundle with Popper -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" crossorigin="anonymous"></script>
    {% block javascript_link %} 
    {% endblock javascript_link %}
</body>
</html>

app/templates/dashboard/org_completed.html
{% extends "dashboard/base.html" %}
{% block title %}Organization Dashboard{% endblock title %}

<!-- external css links -->
{% block css_link %}
    <link rel="stylesheet" type="text/css" href="{{url_for('static', filename='css/sidebars/donor_sidebar.css')}}">
    <link rel="stylesheet" type="text/css" href="{{url_for('static', filename='css/navbars/donor_navbar.css')}}">
    <link rel="stylesheet" type="text/css" href="{{url_for('static', filename='css/collector/completed.css')}}">
{% endblock css_link%}

{% block navbar %}
{% include "includes/navbars/collector_navbar.html" %}
{% endblock navbar %}

{% block main_content %}
<div class="container-fluid">
    <div class="row flex-nowrap">
        {% include "includes/sidebars/collector_sidebar.html" %}
        
        <!-- content -->
        <main class="col ps-md-2 pt-2" id="main-container">
            <section id="section1-main">
                <div class="mini-nav nav">
                    <span><a href="{{url_for('dashboard.to_recieve')}}" class="mini-link">To pick-up/Recieve</a></span>
                    <span><a href="{{url_for('dashboard.to_distribute')}}" class="mini-link">To distribute</a></span>
                    <span><a href="{{url_for('dashboard.completed_collection')}}" class="mini-link active">Completed</a></span>
                    <span></span>
                </div>
            </section>

            <section id="section2-main">
                <!-- <h2 id="donation-collection">Your Donation Collections</h2>   -->

                {%if completed|length == 0 %}
                <center>
                    <div class="empty-feed">
                        <div id="img-container">
                          <img id="icon" src="https://res.cloudinary.com/deh9vgcga/image/upload/v1639958820/empty-cart_fsmwcl.png" alt="">
                        </div>
                        <h3 id="empty-text">Nothing is completed yet.</h3>
                        <a href="{{url_for('collectors_view.collectors_view')}}" class="btn" id="empty-cart-btn">Browse availabe donations</a>
                    </div>
                </center>
                {% endif %}
                {% for donation in completed %}
                <div class="social-feed-box-completed"> 
                    <div class="social-body">
                        {% if donation[4]|length == 0 %} <!--No distribution photos-->
                        <div class="donation">
                            <div id="line"></div>
                            <div class="donation-info">
                                <h3 class="donation-id">From <a href=""><strong>{{ donation[1][0] }}</strong></a></h3>
                                <h4>{{ donation[2] }}</h4>
                                <small>Distributed on {{ donation[3] }}</small>
                                <div class="item-button btn btn btn-success" data-bs-toggle="modal" data-bs-target="#items-gallery{{donation.0}}">
                                  See items
                                </div>
                                <br>
                            </div>
                        </div>
                        {% else %} <!--Has distribution photos-->
                        <div class="social-avatar">
                            <div class="small-donation-details">
                                <small class="text-muted d-flex">From&nbsp;<a href="{{url_for('organization.org_page', org_id=donation[1][1])}}">{{ donation[1][0] }}</a></small>
                                <small class="text-muted d-flex">Date of distribution: {{ donation[3] }}</small>
                            </div>
                        </div>
                        <div class="with-image">
                            <div id="carouselExampleCaptions{{donation.0}}" class="carousel slide" data-bs-ride="carousel">
                                <div class="carousel-indicators">
                                    {% for index in range (0, donation[4]|length) %}
                                    {% if index == 0 %}
                                    <button type="button" data-bs-target="#carouselExampleCaptions" data-bs-slide-to="0" class="active" aria-current="true" aria-label="Slide 1"></button>
                                    {% else %}
                                    <button type="button" data-bs-target="#carouselExampleCaptions" data-bs-slide-to="{{index}}" aria-label="Slide {{index}}"></button>
                                    {% endif %}
                                    {% endfor %}
                                  </div>
                                  <div class="carousel-inner">
                                      {% for img in range(0, donation[4]|length) %}
                                      {% if img == 0 %}
                                      <div class="carousel-item active">
                                        <img id="carousel-img" src="{{donation[4][img]}}" class="d-block w-100 carousel-item-img" alt="...">
                                        <div class="carousel-caption d-none d-md-block">
                                        </div>
                                      </div>
                                      {% else %}
                                      <div class="carousel-item">
                                        <img id="carousel-img" src="{{donation[4][img]}}" class="d-block w-100" alt="...">
                                        <div class="carousel-caption d-none d-md-block">
                                        </div>
                                      </div>
                                      {% endif %}
                                      {% endfor %}
                                  </div>
                                  <button class="carousel-control-prev" type="button" data-bs-target="#carouselExampleCaptions{{donation[0]}}" data-bs-slide="prev">
                                    <span class="carousel-control-prev-icon" aria-hidden="true"></span>
                                    <span class="visually-hidden">Previous</span>
                                  </button>
                                  <button class="carousel-control-next" type="button" data-bs-target="#carouselExampleCaptions{{donation[0]}}" data-bs-slide="next">
                                    <span class="carousel-control-next-icon" aria-hidden="true"></span>
                                    <span class="visually-hidden">Next</span>
                                  </button>
                            </div>
                            <div class="item-button btn btn btn-success" data-bs-toggle="modal" data-bs-target="#items-gallery{{donation.0}}">
                              See items
                          </div>
                            <br>
                        </div>
                        </div>
                        {% endif %}
                </div>
                          <!-- Modal -->
          <div class="modal fade" id="items-gallery{{donation.0}}"
          data-bs-keyboard="false" tabindex="-1" aria-labelledby="staticBackdropLabel"
          aria-hidden="true">
          <div class="modal-dialog">
              <div class="modal-content modal-content-00">
                  <div class="modal-header">
                      <div class="d-flex">
                          <h5>Donation items</h5>
                      </div>
                      <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                  </div>
                  <div class="modal-body modal-body-00">

                    <div id="carouselExampleCaptions{{donation.0}}a" class="carousel slide" data-bs-ride="carousel">
                      <div class="carousel-indicators">
                        {% for index in range (0, donation.5|length) %}
                        {% if index == 0 %}
                        <button type="button" data-bs-target="#carouselExampleCaptions" data-bs-slide-to="0" class="active" aria-current="true" aria-label="Slide 1"></button>
                        {% else %}
                        <button type="button" data-bs-target="#carouselExampleCaptions" data-bs-slide-to="{{index}}" aria-label="Slide {{index+1}}"></button>
                        {% endif %}
                        {% endfor %}
                      </div>
                      <div class="carousel-inner">
                          {% for img in range (0, donation.5|length) %}
                          {% if img == 0 %}
                          <div class="carousel-item active">
                            <img src="{{donation[5][img]}}" class="d-block w-100 carousel-item-img" alt="...">
                          </div>
                          {% else %}
                          <div class="carousel-item">
                            <img src="{{donation[5][img]}}" class="d-block w-100 carousel-item-img" alt="...">
                          </div>
                          {% endif %}
                          {% endfor %}
                      </div>
                      <button class="carousel-control-prev" type="button" data-bs-target="#carouselExampleCaptions{{donation.0}}a" data-bs-slide="prev">
                        <span class="carousel-control-prev-icon" aria-hidden="true"></span>
                        <span class="visually-hidden">Previous</span>
                      </button>
                      <button class="carousel-control-next" type="button" data-bs-target="#carouselExampleCaptions{{donation.0}}a" data-bs-slide="next">
                        <span class="carousel-control-next-icon" aria-hidden="true"></span>
                        <span class="visually-hidden">Next</span>
                      </button>
                    </div>
                  </div>
              </div>
          </div>
      </div>
                {% endfor %}
                
            </section>
        </main>

    </div>
</div>
{% endblock main_content %}

app/templates/dashboard/org_to_collect.html
{% extends "dashboard/base.html" %}
{% block title %}Organization Dashboard{% endblock title %}

<!-- external css links -->
{% block css_link %}
    <link rel="stylesheet" type="text/css" href="{{url_for('static', filename='css/sidebars/donor_sidebar.css')}}">
    <link rel="stylesheet" type="text/css" href="{{url_for('static', filename='css/navbars/donor_navbar.css')}}">
    <link rel="stylesheet" type="text/css" href="{{url_for('static', filename='css/collector/to_collect.css')}}">
{% endblock css_link%}

{% block navbar %}
{% include "includes/navbars/collector_navbar.html" %}
{% endblock navbar %}

{% block main_content %}
<div class="container-fluid">
    <div class="row flex-nowrap">
        {% include "includes/sidebars/collector_sidebar.html" %}
        
        <!-- content -->
        <main class="col ps-md-2 pt-2" id="main-container">
            <section id="section1-main">
                <div class="mini-nav nav">
                    <span><a href="{{url_for('dashboard.to_recieve')}}" class="mini-link active">To pick-up/Recieve</a></span>
                    <span><a href="{{url_for('dashboard.to_distribute')}}" class="mini-link">To distribute</a></span>
                    <span><a href="{{url_for('dashboard.completed_collection')}}" class="mini-link">Completed</a></span>
                    <span></span>
                </div>
            </section>

            <section id="section2-main">
                <!-- <h2 id="donation-collection">Your Donation Collections</h2>   -->

                {%if reserves|length == 0 %}
                <center>
                    <div class="empty-feed">
                        <div id="img-container">
                          <img id="icon" src="https://res.cloudinary.com/deh9vgcga/image/upload/v1639958820/empty-cart_fsmwcl.png" alt="">
                        </div>
                        <h3 id="empty-text">You don't have anything waiting to be collected.</h3>
                        <a href="{{url_for('collectors_view.collectors_view')}}" class="btn" id="empty-cart-btn">Browse availabe donations</a>
                    </div>
                </center>
                {% endif %}
                {% for donation in reserves %}
                <div class="social-avatar">
                    <small class="text-muted d-flex">From&nbsp;<a href="#">{{ donation[1][0] }}</a></small>
                    <small class="text-muted d-flex">Reserved on {{ donation[3] }}</small>
                    {% if donation.5 == 'pick-up' %}
                    <small class="text-muted d-flex">Pick it up at {{ donation[4] }} .</small>
                    {% else %}
                    <small class="text-muted d-flex">Wait for this donation to be delivered at your location.</small>
                    {% endif %}
                </div>
                <div class="with-image">
                    <div id="carouselExampleCaptions{{donation.0}}" class="carousel slide" data-bs-ride="carousel">
                        <div class="carousel-indicators">
                            {% for index in range (0, donation[6]|length) %}
                            {% if index == 0 %}
                            <button type="button" data-bs-target="#carouselExampleCaptions" data-bs-slide-to="0" class="active" aria-current="true" aria-label="Slide 1"></button>
                            {% else %}
                            <button type="button" data-bs-target="#carouselExampleCaptions" data-bs-slide-to="{{index}}" aria-label="Slide {{index}}"></button>
                            {% endif %}
                            {% endfor %}
                          </div>
                          <div class="carousel-inner">
                              {% for img in range(0, donation[6]|length) %}
                              {% if img == 0 %}
                              <div class="carousel-item active">
                                <img id="carousel-img" src="{{donation[6][img]}}" class="d-block w-100 carousel-item-img" alt="...">
                                <div class="carousel-caption d-none d-md-block">
                                </div>
                              </div>
                              {% else %}
                              <div class="carousel-item">
                                <img id="carousel-img" src="{{donation[6][img]}}" class="d-block w-100 carousel-item-img" alt="...">
                                <div class="carousel-caption d-none d-md-block">
                                </div>
                              </div>
                              {% endif %}
                              {% endfor %}
                          </div>
                          <button class="carousel-control-prev" type="button" data-bs-target="#carouselExampleCaptions{{donation[0]}}" data-bs-slide="prev">
                            <span class="carousel-control-prev-icon" aria-hidden="true"></span>
                            <span class="visually-hidden">Previous</span>
                          </button>
                          <button class="carousel-control-next" type="button" data-bs-target="#carouselExampleCaptions{{donation[0]}}" data-bs-slide="next">
                            <span class="carousel-control-next-icon" aria-hidden="true"></span>
                            <span class="visually-hidden">Next</span>
                          </button>
                    </div>
                    <center>
                        {% if donation.5 == 'pick-up' %}
                        <a href="{{url_for('dashboard.recieve_collect', id=donation[0])}}" class="btn btn-success btn-recieved">Picked</a>
                        {% else %}
                        <a href="{{url_for('dashboard.recieve_collect', id=donation[0])}}" class="btn btn-success btn-recieved">Picked</a>
                        {% endif %}
                        <a href="{{url_for('dashboard.collect_cancel', id=donation[0])}}" class="btn btn-outline-danger btn-cancel"><h6 id="dist-text">Cancel</h6></a>
                    </center>
                </div>

                {% endfor %}
                
            </section>
        </main>

    </div>
</div>
{% endblock main_content %}

app/templates/dashboard/org_to_distribute.html
{% extends "dashboard/base.html" %}
{% block title %}Organization Dashboard{% endblock title %}

<!-- external css links -->
{% block css_link %}
    <link rel="stylesheet" type="text/css" href="{{url_for('static', filename='css/sidebars/donor_sidebar.css')}}">
    <link rel="stylesheet" type="text/css" href="{{url_for('static', filename='css/navbars/donor_navbar.css')}}">
    <link rel="stylesheet" type="text/css" href="{{url_for('static', filename='css/collector/to_distribute.css')}}">
{% endblock css_link%}


{% block navbar %}
{% include "includes/navbars/collector_navbar.html" %}
{% endblock navbar %}

{% block main_content %}
<div class="container-fluid">
    <div class="row flex-nowrap">
        {% include "includes/sidebars/collector_sidebar.html" %}
        
        <!-- content -->
        <main class="col ps-md-2 pt-2" id="main-container">
            <section id="section1-main">
                <div class="mini-nav nav">
                    <span><a href="{{url_for('dashboard.to_recieve')}}" class="mini-link">To pick-up/Recieve</a></span>
                    <span><a href="{{url_for('dashboard.to_distribute')}}" class="mini-link active">To distribute</a></span>
                    <span><a href="{{url_for('dashboard.completed_collection')}}" class="mini-link">Completed</a></span>
                    <span></span>
                </div>
            </section>

            <section id="section2-main">
                <!-- <h2 id="donation-collection">Your Donation Collections</h2>   -->
                {%if collections|length == 0 %}
                <center>
                    <div class="empty-feed">
                        <div id="img-container">
                          <img id="icon" src="https://res.cloudinary.com/deh9vgcga/image/upload/v1639959545/celebrate_f0ee8o.png" alt="">
                        </div>
                        <h3 id="empty-text">Nothing to distribute yet!</h3>
                        <a href="{{url_for('collectors_view.collectors_view')}}" class="btn" id="empty-cart-btn">Browse availabe donations</a>
                    </div>
                </center>
                {%endif%}

                {% for donation in collections %}
                <div class="social-avatar">
                    <small class="text-muted d-flex">From&nbsp;<a href="#">{{ donation[1][0] }}</a></small>
                    <small class="text-muted d-flex">Date of collection: {{ donation[3] }}</small>
                </div>
                <div class="with-image">
                    <div id="carouselExampleCaptions{{donation.0}}" class="carousel slide" data-bs-ride="carousel">
                        <div class="carousel-indicators">
                            {% for index in range (0, donation[4]|length) %}
                            {% if index == 0 %}
                            <button type="button" data-bs-target="#carouselExampleCaptions" data-bs-slide-to="0" class="active" aria-current="true" aria-label="Slide 1"></button>
                            {% else %}
                            <button type="button" data-bs-target="#carouselExampleCaptions" data-bs-slide-to="{{index}}" aria-label="Slide {{index}}"></button>
                            {% endif %}
                            {% endfor %}
                          </div>
                          <div class="carousel-inner">
                              {% for img in range(0, donation[4]|length) %}
                              {% if img == 0 %}
                              <div class="carousel-item active">
                                <img id="carousel-img" src="{{donation[4][img]}}" class="d-block w-100 carousel-item-img" alt="...">
                                <div class="carousel-caption d-none d-md-block">
                                </div>
                              </div>
                              {% else %}
                              <div class="carousel-item">
                                <img id="carousel-img" src="{{donation[4][img]}}" class="d-block w-100 carousel-item-img" alt="...">
                                <div class="carousel-caption d-none d-md-block">
                                </div>
                              </div>
                              {% endif %}
                              {% endfor %}
                          </div>
                          <button class="carousel-control-prev" type="button" data-bs-target="#carouselExampleCaptions{{donation[0]}}" data-bs-slide="prev">
                            <span class="carousel-control-prev-icon" aria-hidden="true"></span>
                            <span class="visually-hidden">Previous</span>
                          </button>
                          <button class="carousel-control-next" type="button" data-bs-target="#carouselExampleCaptions{{donation[0]}}" data-bs-slide="next">
                            <span class="carousel-control-next-icon" aria-hidden="true"></span>
                            <span class="visually-hidden">Next</span>
                          </button>
                    </div>
                    <center>
                        <a class="btn btn-distribute btn-success"
                        data-bs-toggle="modal" data-bs-target="#add-photo-modal{{ donation.0 }}">
                            <h6 id="dist-text">Distribute</h6>
                        </a>
                    </center>
                </div>

                <div class="modal fade" id="add-photo-modal{{ donation.0 }}"
                    data-bs-keyboard="false" tabindex="-1" aria-labelledby="staticBackdropLabel"
                    aria-hidden="true">
                    <div class="modal-dialog">
                        <form action="{{url_for('dashboard.distribute', id=donation[0])}}" method="POST" enctype="multipart/form-data">
                            <div class="modal-content modal-content-00">
                                <div class="modal-header">
                                    <div class="d-flex">
                                        <h6>You may add distribution pictures for the donors to see.</h6>
                                    </div>
                                    <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                                </div>
                                <div class="modal-body modal-body-00">
                                    <div class="row mb-2 image-container">
                                        {% for box in range(1, 4) %}
                                        <div class="image-wrapper">
                                            <div class="image{{box}}">
                                                <img id="image{{box}}" src="https://res.cloudinary.com/deh9vgcga/image/upload/v1641307684/upload-image-icon-png-29_eiz73b.png" alt="" class="d-block ui-w-80">
                                                <input type="file" id="file-btn{{box}}" name="image_file{{box}}" accept="image/png, image/jpeg"  hidden>
                                            </div>
                                        </div>
                                        {% endfor %}
                                        <div class="button-wrapper">
                                          <a onclick="fileBtnActive()" id="upload-btn" class="btn" >Choose a file</a>
                                        </div>
                                    </div>
                                </div>
                                <div class="modal-footer">
                                    <button type="submit" class="btn btn-success">Upload</button>
                                    <button type="button" class="btn btn-outline-success" data-bs-dismiss="modal">Cancel</button>
                                </div>
                            </div>
                        </form>
                    </div>
                </div>

                {% endfor %}
                
            </section>
        </main>

    </div>
</div>


{% endblock main_content %}

{% block javascript_link %} 
<script src="{{ url_for('static', filename='js/distribution.js') }}"></script>
{% endblock javascript_link %}